version: '3.8'

services:
  angular-service:
    container_name: angular-container
    image: hjk  # Use the official Node.js 16 image
    volumes:
      - './:/usr/src/app'
    ports:
      - "4200:4200"
    command: ["npm", "start"]

  docker-nginx:
    container_name: docker-nginx
    image: nginx:latest
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - angular-service
